name: macos

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  macos1015:
    runs-on: macos-latest

    env:
      OPENCV_VERSION: 4.8.1
      PKG_NAME: opencv-4.8.1-macos1015

    steps:
      # Setup JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # 检出代码
      - uses: actions/checkout@v2

      # 检出opencv
      - name: checkout opencv
        uses: actions/checkout@v2
        with:
          repository: opencv/opencv
          path: opencv-${{ env.OPENCV_VERSION }}
          ref: ${{ env.OPENCV_VERSION }}
          submodules: recursive

      # 安装openmp
      - name: install openmp
        run: |
          brew install libomp

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-opencv4.sh opencv-${{ env.OPENCV_VERSION }}
          cp opencv4_cmake_options.txt opencv-${{ env.OPENCV_VERSION }}

      # 编译opencv for macos
      - name: build opencv
        run: |
          cd opencv-${{ env.OPENCV_VERSION }}
          chmod a+x build-opencv4.sh &&./build-opencv4.sh

      # install文件夹改名macos，并使用7z压缩
      - name: rename
        run: |
          mv opencv-${{ env.OPENCV_VERSION }}/build-Release/install macos
          7z a ${{ env.PKG_NAME }}.7z macos

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_NAME }}.7z

      # 获取所有的git log和tag
      - name: Unshallow
        run: git fetch --prune --unshallow

      # 获取git log 从 previousTag 到 lastTag
      - name: Get git log
        id: git-log
        run: |
          previousTag=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          lastTag=$(git describe --abbrev=0 --tags)
          echo "previousTag:$previousTag ~ lastTag:$lastTag"
          log=$(git log $previousTag..$lastTag --pretty=format:'- %cd %an: %s\n' --date=format:'%Y-%m-%d %H:%M:%S')
          echo "$log"
          echo "log_state="$log"" >> $GITHUB_ENV

      # 创建Changelog文件 triggered by git tag push
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo -e '${{ env.log_state }}' > release.md

      # 创建release 上传release
      # https://github.com/marketplace/actions/create-release
      - name: Create release and upload-archive
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          name: opencv-lite ${{ github.ref }}
          bodyFile: release.md
          artifacts: ${{ env.PKG_NAME }}.7z
          allowUpdates: true
          artifactContentType: application/x-7z-compressed
          token: ${{ secrets.GITHUB_TOKEN }}