name: macos

on:
  workflow_dispatch:

jobs:
  macos1015:
    runs-on: macos-latest

    env:
      OPENCV_VERSION: 4.5.2
      PKG_NAME: opencv-4.5.2-macos1015

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 检出opencv
      - name: checkout opencv
        uses: actions/checkout@v2
        with:
          repository: opencv/opencv
          path: opencv-${{ env.OPENCV_VERSION }}
          ref: ${{ env.OPENCV_VERSION }}
          submodules: recursive

      # 安装openmp
      - name: install openmp
        run: |
          brew install libomp

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-opencv4.sh opencv-${{ env.OPENCV_VERSION }}
          cp opencv4_cmake_options.txt opencv-${{ env.OPENCV_VERSION }}

      # 编译opencv for macos
      - name: build opencv
        run: |
          cd opencv-${{ env.OPENCV_VERSION }}
          chmod a+x build-opencv4.sh &&./build-opencv4.sh

      # install文件夹改名macos，并使用7z压缩
      - name: rename
        run: |
          mv opencv-${{ env.OPENCV_VERSION }}/build-Release/install macos
          7z a ${{ env.PKG_NAME }}.7z macos

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_NAME }}.7z
