name: windows

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        ver:
          - { cv: 3.4.16, ant: 1.10.14 }
        list:
          - { win_ver: 2019, vs_name: vs2015, vs_ver: v140 }
          - { win_ver: 2019, vs_name: vs2017, vs_ver: v141 }
          - { win_ver: 2019, vs_name: vs2019, vs_ver: v142 }
          - { win_ver: 2022, vs_name: vs2022, vs_ver: v143 }
        crt:
          [
            md,
            mt,
          ]

    runs-on: windows-${{ matrix.list.win_ver }}

    name: windows-${{ matrix.list.vs_name }}-${{ matrix.crt }}

    env:
      PKG_NAME: opencv-${{ matrix.ver.cv }}-windows-${{ matrix.list.vs_name }}-${{ matrix.crt }}
      JAVA_PKG_NAME: opencv-${{ matrix.ver.cv }}-windows-${{ matrix.list.vs_name }}-java-${{ matrix.crt }}

    steps:
      # Setup JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: cedx/setup-ant@v2
        with:
          optional-tasks: true
          version: ${{ matrix.ver.ant }}

      - name: ant version
        run: ant -version

      # 检出代码
      - uses: actions/checkout@v3

      # 检出opencv
      - name: checkout opencv
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
          path: opencv-${{ matrix.ver.cv }}
          ref: ${{ matrix.ver.cv }}
          submodules: recursive

      # 复制
      - name: copy
        run: |
          cp build-opencv3.bat opencv-${{ matrix.ver.cv }}
          cp build-opencv3-java.bat opencv-${{ matrix.ver.cv }}
          cp opencv3_cmake_options.txt opencv-${{ matrix.ver.cv }}

      # 编译
      # https://github.com/ilammy/msvc-dev-cmd
      #- uses: ilammy/msvc-dev-cmd@v1
      - name: build
        run: |
          cd opencv-${{ matrix.ver.cv }}
          ./build-opencv3.bat ${{ matrix.list.vs_ver }} ${{ matrix.crt }}

      # 7z压缩
      - name: 7zip
        run: |
          cp -r opencv-${{ matrix.ver.cv }}/build-x64-${{ matrix.list.vs_ver }}-${{ matrix.crt }}/install windows-x64
          cp -r opencv-${{ matrix.ver.cv }}/build-Win32-${{ matrix.list.vs_ver }}-${{ matrix.crt }}/install windows-x86
          7z a ${{ env.PKG_NAME }}.7z windows-x64 windows-x86
          rm windows-x64 -r -fo
          rm windows-x86 -r -fo

      - name: build java
        run: |
          cd opencv-${{ matrix.ver.cv }}
          ./build-opencv3-java.bat ${{ matrix.list.vs_ver }} ${{ matrix.crt }}

      # 7z压缩
      - name: 7zip
        run: |
          cp -r opencv-${{ matrix.ver.cv }}/build-x64-${{ matrix.list.vs_ver }}-${{ matrix.crt }}/install/java windows-x64
          cp -r opencv-${{ matrix.ver.cv }}/build-Win32-${{ matrix.list.vs_ver }}-${{ matrix.crt }}/install/java windows-x86
          7z a ${{ env.JAVA_PKG_NAME }}.7z windows-x64 windows-x86
          rm windows-x64 -r -fo
          rm windows-x86 -r -fo

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_NAME }}.7z

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.JAVA_PKG_NAME }}
          path: ${{ env.JAVA_PKG_NAME }}.7z

  release:
    needs: [ windows ]

    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 获取所有的git log和tag
      - name: Unshallow
        run: git fetch --prune --unshallow

      # 获取git log 从 previousTag 到 lastTag
      - name: Get git log
        id: git-log
        run: |
          previousTag=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          lastTag=$(git describe --abbrev=0 --tags)
          echo "previousTag:$previousTag ~ lastTag:$lastTag"
          log=$(git log $previousTag..$lastTag --pretty=format:'- %cd %an: %s\n' --date=format:'%Y-%m-%d %H:%M:%S')
          echo "$log"
          echo "log_state="$log"" >> $GITHUB_ENV

      # 创建Changelog文件 triggered by git tag push
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo -e '${{ env.log_state }}' > release.md

      # 下载artifact
      - name: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      # 查看artifact
      - name: list artifact
        run: |
          tree artifacts

      # 创建release 上传release
      # https://github.com/marketplace/actions/create-release
      - name: upload-windows
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          bodyFile: release.md
          artifacts: artifacts/*/*.7z
          allowUpdates: true
          artifactContentType: application/x-7z-compressed
          token: ${{ secrets.GITHUB_TOKEN }}
