name: windows-vs2017

on:
  workflow_dispatch:

jobs:
  windows-vs2017:
    runs-on: windows-2016

    env:
      OPENCV_VERSION: 4.6.0
      PKG_NAME: opencv-4.6.0-windows-vs2017

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 检出opencv
      - name: checkout opencv
        uses: actions/checkout@v2
        with:
          repository: opencv/opencv
          path: opencv-${{ env.OPENCV_VERSION }}
          ref: ${{ env.OPENCV_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-opencv4-vs2017.bat opencv-${{ env.OPENCV_VERSION }}
          cp opencv4_cmake_options.txt opencv-${{ env.OPENCV_VERSION }}

      # 编译opencv for windows
      # https://github.com/ilammy/msvc-dev-cmd
      #- uses: ilammy/msvc-dev-cmd@v1
      - name: build opencv
        run: |
          cd opencv-${{ env.OPENCV_VERSION }}
          ./build-opencv4-vs2017.bat

      # install文件夹改名，并使用7z压缩
      - name: 7z-md
        run: |
          mv opencv-${{ env.OPENCV_VERSION }}/build-v141-x64-md/install windows-x64
          mv opencv-${{ env.OPENCV_VERSION }}/build-v141-Win32-md/install windows-x86
          7z a ${{ env.PKG_NAME }}-md.7z windows-x64 windows-x86
          rm windows-x64 -r -fo
          rm windows-x86 -r -fo

      # 上传artifact
      - name: upload-md
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}-md
          path: |
            ${{ env.PKG_NAME }}-md.7z

      # install文件夹改名，并使用7z压缩
      - name: 7z-mt
        run: |
          mv opencv-${{ env.OPENCV_VERSION }}/build-v141-x64-mt/install windows-x64
          mv opencv-${{ env.OPENCV_VERSION }}/build-v141-Win32-mt/install windows-x86
          7z a ${{ env.PKG_NAME }}-mt.7z windows-x64 windows-x86
          rm windows-x64 -r -fo
          rm windows-x86 -r -fo

      # 上传artifact
      - name: upload-mt
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}-mt
          path: |
            ${{ env.PKG_NAME }}-mt.7z
