name: windows-vs2019

on:
  workflow_dispatch:

jobs:
  windows-vs2019:
    runs-on: windows-2019

    env:
      OPENCV_VERSION: 4.5.1
      PKG_NAME: opencv-4.5.1-windows-vs2019

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 检出opencv
      - name: checkout opencv
        uses: actions/checkout@v2
        with:
          repository: opencv/opencv
          path: opencv-${{ env.OPENCV_VERSION }}
          ref: ${{ env.OPENCV_VERSION }}
          submodules: recursive

      # 复制编译脚本
      - name: copy build script
        run: |
          cp build-opencv4-vs2019.bat opencv-${{ env.OPENCV_VERSION }}
          cp opencv4_cmake_options.txt opencv-${{ env.OPENCV_VERSION }}

      # 编译opencv for windows
      # https://github.com/ilammy/msvc-dev-cmd
      #- uses: ilammy/msvc-dev-cmd@v1
      - name: build opencv
        run: |
          cd opencv-${{ env.OPENCV_VERSION }}
          ./build-opencv4-vs2019.bat

      # install文件夹改名，并使用7z压缩
      - name: rename
        run: |
          mv opencv-${{ env.OPENCV_VERSION }}/build-v142-x64/install windows-x64
          mv opencv-${{ env.OPENCV_VERSION }}/build-v142-Win32/install windows-x86
          7z a ${{ env.PKG_NAME }}.7z windows-x64 windows-x86

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKG_NAME }}
          path: |
            ${{ env.PKG_NAME }}.7z
